# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d45f3ef596bae65447f825a256044e2f31299c174710d8cd2b11d0e7d6c6a130a66ef468cd1c5ebb9654932b38acba1ddeaa096991690925e7e5285a645adf7

test:
  secret_key_base: 1b24d3343ae89607bcfa9b78193c2fba983f3a6193df581d5e09ae5d4333e7c92bd54c8067a2746b52fe4720bcdc7af55a17c2ac0fd4eebfecbb493ec9dc2bff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
